<?php
$pcaAccCode = Mage::getStoreConfig('captureplus/settings/account_code');
$pcaCustomCode = Mage::getStoreConfig('captureplus/settings/custom_code');
$pcaMappings = Mage::getStoreConfig('captureplus/settings/custom_mappings');
if($pcaAccCode) {
?>

<script type="text/javascript">

      (function (a, c, b, e) {
    a[b] = a[b] || {}; a[b].initial = { accountCode: "<?php echo $pcaAccCode; ?>", host: "<?php echo $pcaAccCode; ?>.pcapredict.com" };
    a[b].on = a[b].on || function () { (a[b].onq = a[b].onq || []).push(arguments) }; var d = c.createElement("script");
    d.async = !0; d.src = e; c = c.getElementsByTagName("script")[0]; c.parentNode.insertBefore(d, c)
    })(window, document, "pca", "//<?php echo $pcaAccCode; ?>.pcapredict.com/js/sensor.js");

//<![CDATA[
  (function() {
     var magento = pca.magento = pca.magento || {};

     magento.controls = magento.controls || [];
     var capturePlusFields = [];
      
      pca.on('data', function(source, key, address, variations) {
            switch(source) {
                case 'address':
                    for (var i = 0; i < capturePlusFields.length; i++) {
                        var el = document.getElementById(capturePlusFields[i].element);
                        if (el) {
                            pca.fire(el, 'change');
                        }
                    }
                break;

                default: 
                    break;
            }
        });
        
            magento.canLoad = function() {
            // check to see if we have the form fields                    
            if (pca
                && pca.platform
                && typeof pca.platform.elementExists === 'function' 
                && (pca.platform.elementExists("billing:street1"))) {
                    
                //load pca
                pca.load();
            }
            else {
                // re-set the timout
                window.setTimeout(magento.canLoad, 500);
            }
        }
        
        magento.onload = function(func) {
            // assign any pre-defined functions on 'window.onload' to a variable
            var oldOnLoad = window.onload;
            // if there is not any function hooked to it
            if (typeof window.onload !== 'function') {
                // you can hook your function with it
                window.onload = func
            } else { // someone already hooked a function
                window.onload = function () {
                    // call the function hooked already
                    oldOnLoad();
                    // call your awesome function
                    func();
                }
            }
        }

        //wait for the page to be ready
        magento.onload(function() {
            window.setTimeout(magento.canLoad, 500);
        });

        pca.on('ready', function ()
        {
            pca.sourceString = 'MagentoExtension-v3.0.7';
        });

                pca.on('restrictions', function (service, key, restrictions) {
            switch (service) {
                case 'capture+': 
                //case 'mobilevalidation':
                //case 'emailvalidation': 
                    restrictions.length = 0;
                    break;
                default: 
                    break;
            }
            
        });


        pca.on("fields", function(service, id, fields) {       
            
            var capturePlusMappings = [];
             //var phoneMappings = [];
             //var emailMappings = [];
            <?php echo $pcaMappings; ?>

            switch (service) {
                case 'capture+':

                if (capturePlusMappings.length > 0) {

                    var newCPMappings = [];
                    for (var i = 0; i < capturePlusMappings.length; i++) {
                        newCPMappings.push(capturePlusMappings[i]);
                    }
                }
                fields.length = 0;
                for (var i = 0; i < newCPMappings.length; i++) {
                    fields.push(newCPMappings[i]);
                    var fieldAlreadyFound = false;
                    for (var ii = 0; ii < capturePlusFields.length; ii++) {
                        if (capturePlusFields[ii].element === newCPMappings[i].element) {
                            fieldAlreadyFound = true;
                            break;
                        }
                    }
                    if (fieldAlreadyFound != true) 
                        capturePlusFields.push(newCPMappings[i]);
                } 
                break;

                    // case 'mobilevalidation':
                    // if (phoneMappings.length > 0) {
                    //     fields.length = 0;     
                    //     var newMobileMappings = [];                    
                    //     for (var i = 0; i < phoneMappings.length; i++) {
                    //         var dynamicMobField = document.getElementById(phoneMappings[i].element);
                    //         if (dynamicMobField) {
                    //             var newMapping = {};
                    //             newMapping.field = phoneMappings[i].field;
                    //             newMapping.mode = phoneMappings[i].mode;
                    //             newMapping.element = dynamicMobField.id;
                    //             newMobileMappings.push(newMapping);
                    //         }
                    //     }             
                    //     if (newMobileMappings.length > 0) {
                    //         phoneMappings = [];
                    //         for (var i = 0; i < newMobileMappings.length; i++) {
                    //             fields.push(newMobileMappings[i]);
                    //             phoneMappings.push(newMobileMappings[i]);
                    //         }
                    //     }                     
                    // }
                    // break;

                default: 
                    break;
            }
        });

        var registerButton = document.getElementById("onepage-guest-register-button");
        if (registerButton) {
            registerButton.addEventListener("click", function() {
                pca.load();
            });
        }
        
    <?php
    if($pcaCustomCode) {
        echo $pcaCustomCode;
    }
    ?>

    })();
//]]>
</script>
<?php }