<?php
$pcaAccCode = Mage::getStoreConfig('captureplus/settings/account_code');
if($pcaAccCode) {
?>

<script type="text/javascript">

      (function (a, c, b, e) {
    a[b] = a[b] || {}; a[b].initial = { accountCode: "<?php echo $pcaAccCode; ?>", host: "<?php echo $pcaAccCode; ?>.pcapredict.com" };
    a[b].on = a[b].on || function () { (a[b].onq = a[b].onq || []).push(arguments) }; var d = c.createElement("script");
    d.async = !0; d.src = e; c = c.getElementsByTagName("script")[0]; c.parentNode.insertBefore(d, c)
    })(window, document, "pca", "//<?php echo $pcaAccCode; ?>.pcapredict.com/js/sensor.js");

//<![CDATA[
  (function() {
     var magento = pca.magento = pca.magento || {};
     
     magento.controls = magento.controls || [];
     var capturePlusFields = [];
      
      pca.on('data', function(source, key, address, variations) {
            console.log(source);
            console.log(key);
            console.log(address);
            console.log(variations);
            
            for (var i = 0; i < capturePlusFields.length; i++) {
                var el = document.getElementById(capturePlusFields[i].element);
                if (el) {
                    pca.fire(el, 'change');
                }
            }
        });
        
        pca.on('ready', function ()
        {
            pca.sourceString = 'MagentoExtension-v3.0.0';
        })
        
    })();
//]]>
</script>
<?php }