<?php
?>

<script type="text/javascript">

    window.onload = function() {
        var el = document.getElementById("captureplus_login_license_key");
        if(el) {
            hideFields();
        
            if(el.value=='') {
                var feedback = document.getElementById("captureplus_login_feedback");
                if (feedback) {
                    feedback.innerHTML = 'You are not logged in';
                    updateLoginHeader("Log in to PCA Predict");
                    updateButton("Login");
                    disableLoginFields(false);
                    notLoggedIn();
                }
            } else {
                var feedback = document.getElementById("captureplus_login_feedback");
                if (feedback) {
                    feedback.innerHTML = 'You are logged in';
                    updateLoginHeader("Your PCA Predict Account");
                    updateButton("Logout");
                    disableLoginFields(true);
                    loggedIn();
                }
            }
        }
    }

    function hideFields() {
        var el3 = document.getElementById("row_captureplus_login_mercury_token");
        if(el3) {
            el3.style.visibility = "hidden";
            
            var ele3Val = document.getElementById("captureplus_login_mercury_token");
            if (ele3Val) {
                ele3Val.disabled = true; 
            }
        }
    }

    function notLoggedIn() {
        //Try and hide settings if the child is there and the parent is a "section-config" class.
        var me = document.getElementById("captureplus_settings");
        
        if(me && (me.parentElement.className == "section-config" || me.parentElement.className == "section-config active")){
            me.parentElement.style.visibility = "hidden";
        }
    }

    function loggedIn() {
        //Try and hide settings if the child is there and the parent is a "section-config" class.
        var me = document.getElementById("captureplus_settings");
        
        if(me && (me.parentElement.className == "section-config" || me.parentElement.className == "section-config active")){
            me.parentElement.style.visibility = "visible";
        }
    }

    function updateLoginHeader(title) {
        var head = document.getElementById("captureplus_login-head");
        if(head) {
            head.innerHTML = title;
        }
    }

    function updateButton(title) {
        var btn = document.getElementById("postcodeanywherecaptureplus_button");
        if(btn) {
            btn.title = title;
            btn.disabled = false;
            btn.innerHTML = "<span><span><span>" + title + "</span></span></span>";
        }
    }

    function disableLoginFields(disabled) {
        var username = document.getElementById("captureplus_login_account_code");
        if (username) {
            username.disabled = disabled; 
        }

        var password = document.getElementById("captureplus_login_pca_password");
        if (password) {
            password.disabled = disabled;
        }
    }

    function getCollapsedState(containerId) {
        var collapsed = 0;

        if ($(containerId + '-state')) {
            collapsed = $(containerId + '-state').value == 1 ? 0 : 1;
        } else {
            collapsed = $(containerId + '-head').collapsed;
        }

        return collapsed;
    }

    function getAuth() {
        var txtAccountCode = document.getElementById("captureplus_login_account_code");
        if(txtAccountCode) {
            var txtToken = document.getElementById("captureplus_login_mercury_token");
            if(txtToken) {
                return btoa(txtAccountCode.value + ':' + txtToken.value);
            }
        }
    }

    function formatDate(date) {
        var hours = date.getHours();
        var minutes = date.getMinutes();
        var ampm = hours >= 12 ? 'pm' : 'am';
        hours = hours % 12;
        hours = hours ? hours : 12; // the hour '0' should be '12'
        minutes = minutes < 10 ? '0'+minutes : minutes;
        var strTime = hours + ':' + minutes + ' ' + ampm;
        return date.getMonth()+1 + "/" + date.getDate() + "/" + date.getFullYear();
    }

</script>