<?php
?>

<script type="text/javascript">
    
    window.onload = function() {
        var mercuryTokenElement = document.getElementById("addresslookup_options_login_mercury_token");
        var feedbackElement = document.getElementById("addresslookup_options_login_feedback");
        var headerElement = document.getElementById("addresslookup_options_login-head");
        var loginButtonElement = document.getElementById("addressyaddresslookup_button");
        var accountCodeInputElement = document.getElementById("addresslookup_options_login_account_code");
        var passwordInputElement = document.getElementById("addresslookup_options_login_pca_password");
        var passwordInputRow = document.getElementById("row_addresslookup_options_login_pca_password");

        if(mercuryTokenElement) {
            
            var loggedIn = false;
            if(mercuryTokenElement.value != ''){
                loggedIn = true;
            }

            mercuryTokenElement.disabled = loggedIn;

            if(feedbackElement){
                feedbackElement.innerHTML = loggedIn ? "You are logged in" : "You are not logged in"
            }

            
            if(headerElement) {
                headerElement.innerHTML = loggedIn ? "Your Addressy Account" : "Log in to Addressy";
            }

            if(loginButtonElement){
                loginButtonElement.disabled = false;
                loginButtonElement.title = loggedIn ? "Logout" : "Login";
                loginButtonElement.innerHTML = "<span><span><span>" + (loggedIn ? "Logout" : "Login") + "</span></span></span>";
            }

            if(passwordInputRow){
                passwordInputRow.style.display = loggedIn ? "none" : "";
            }

            if(passwordInputElement){
                passwordInputElement.disabled = loggedIn;
            }

            if(accountCodeInputElement){
                accountCodeInputElement.disabled = loggedIn;
            }
        }
    }


</script>