<?php

    $pcaAccCode = Mage::getStoreConfig('addresslookup_options/login/account_code');

    $pcaCustomCode = Mage::getStoreConfig('addresslookup_options/settings/custom_code_frontend');

    if($pcaAccCode) {
?>

<script type="text/javascript">

   

    (function (a, c, b, e) {
    a[b] = a[b] || {}; a[b].initial = { accountCode: "<?php echo $pcaAccCode; ?>", host: "<?php echo $pcaAccCode; ?>.addressy.com" };
    a[b].on = a[b].on || function () { (a[b].onq = a[b].onq || []).push(arguments) }; var d = c.createElement("script");
    d.async = !0; d.src = e; c = c.getElementsByTagName("script")[0]; c.parentNode.insertBefore(d, c)
})(window, document, "pca", "//<?php echo $pcaAccCode; ?>.addressy.com/js/sensor.js");

   
        
    <?php
        if($pcaCustomCode) {
            echo $pcaCustomCode;
        }
    ?>

</script>
<?php } ?>